// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_real_time_chat/test/features/chat/domain/usecases/get_messages_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_real_time_chat/core/errors/failures.dart' as _i6;
import 'package:flutter_real_time_chat/features/chat/domain/entities/chat_room.dart'
    as _i5;
import 'package:flutter_real_time_chat/features/chat/domain/entities/message.dart'
    as _i7;
import 'package:flutter_real_time_chat/features/chat/domain/repositories/chat_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i3.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i5.ChatRoom>> get chatRoomsStream => (super.noSuchMethod(
        Invocation.getter(#chatRoomsStream),
        returnValue: _i4.Stream<List<_i5.ChatRoom>>.empty(),
      ) as _i4.Stream<List<_i5.ChatRoom>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, List<_i5.ChatRoom>>> getChatRooms() =>
      (super.noSuchMethod(
        Invocation.method(
          #getChatRooms,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, List<_i5.ChatRoom>>>.value(
                _FakeEither_0<_i6.Failure, List<_i5.ChatRoom>>(
          this,
          Invocation.method(
            #getChatRooms,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, List<_i5.ChatRoom>>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.ChatRoom>> createChatRoom({
    required String? name,
    required String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createChatRoom,
          [],
          {
            #name: name,
            #description: description,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i5.ChatRoom>>.value(
            _FakeEither_0<_i6.Failure, _i5.ChatRoom>(
          this,
          Invocation.method(
            #createChatRoom,
            [],
            {
              #name: name,
              #description: description,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i5.ChatRoom>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.ChatRoom>> joinChatRoom(
          {required String? roomId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinChatRoom,
          [],
          {#roomId: roomId},
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i5.ChatRoom>>.value(
            _FakeEither_0<_i6.Failure, _i5.ChatRoom>(
          this,
          Invocation.method(
            #joinChatRoom,
            [],
            {#roomId: roomId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i5.ChatRoom>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> leaveChatRoom(
          {required String? roomId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #leaveChatRoom,
          [],
          {#roomId: roomId},
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #leaveChatRoom,
            [],
            {#roomId: roomId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, List<_i7.Message>>> getMessages({
    required String? roomId,
    int? limit,
    String? lastMessageId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [],
          {
            #roomId: roomId,
            #limit: limit,
            #lastMessageId: lastMessageId,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, List<_i7.Message>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.Message>>(
          this,
          Invocation.method(
            #getMessages,
            [],
            {
              #roomId: roomId,
              #limit: limit,
              #lastMessageId: lastMessageId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, List<_i7.Message>>>);

  @override
  _i4.Stream<List<_i7.Message>> getMessagesStream({required String? roomId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessagesStream,
          [],
          {#roomId: roomId},
        ),
        returnValue: _i4.Stream<List<_i7.Message>>.empty(),
      ) as _i4.Stream<List<_i7.Message>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i7.Message>> sendMessage({
    required String? roomId,
    required String? content,
    required _i7.MessageType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [],
          {
            #roomId: roomId,
            #content: content,
            #type: type,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i7.Message>>.value(
            _FakeEither_0<_i6.Failure, _i7.Message>(
          this,
          Invocation.method(
            #sendMessage,
            [],
            {
              #roomId: roomId,
              #content: content,
              #type: type,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i7.Message>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> markMessageAsRead({
    required String? messageId,
    required String? roomId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMessageAsRead,
          [],
          {
            #messageId: messageId,
            #roomId: roomId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #markMessageAsRead,
            [],
            {
              #messageId: messageId,
              #roomId: roomId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> markAllMessagesAsRead(
          {required String? roomId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAllMessagesAsRead,
          [],
          {#roomId: roomId},
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #markAllMessagesAsRead,
            [],
            {#roomId: roomId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i7.Message>> updateMessage({
    required String? messageId,
    required String? newContent,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMessage,
          [],
          {
            #messageId: messageId,
            #newContent: newContent,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i7.Message>>.value(
            _FakeEither_0<_i6.Failure, _i7.Message>(
          this,
          Invocation.method(
            #updateMessage,
            [],
            {
              #messageId: messageId,
              #newContent: newContent,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i7.Message>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> deleteMessage({
    required String? messageId,
    required String? roomId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMessage,
          [],
          {
            #messageId: messageId,
            #roomId: roomId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #deleteMessage,
            [],
            {
              #messageId: messageId,
              #roomId: roomId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, int>> getUnreadMessageCount(
          {required String? roomId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnreadMessageCount,
          [],
          {#roomId: roomId},
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, int>>.value(
            _FakeEither_0<_i6.Failure, int>(
          this,
          Invocation.method(
            #getUnreadMessageCount,
            [],
            {#roomId: roomId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, int>> getTotalUnreadMessageCount() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalUnreadMessageCount,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, int>>.value(
            _FakeEither_0<_i6.Failure, int>(
          this,
          Invocation.method(
            #getTotalUnreadMessageCount,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, List<_i7.Message>>> searchMessages({
    required String? roomId,
    required String? query,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMessages,
          [],
          {
            #roomId: roomId,
            #query: query,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, List<_i7.Message>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.Message>>(
          this,
          Invocation.method(
            #searchMessages,
            [],
            {
              #roomId: roomId,
              #query: query,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, List<_i7.Message>>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.ChatRoom>> getChatRoomById(
          {required String? roomId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChatRoomById,
          [],
          {#roomId: roomId},
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i5.ChatRoom>>.value(
            _FakeEither_0<_i6.Failure, _i5.ChatRoom>(
          this,
          Invocation.method(
            #getChatRoomById,
            [],
            {#roomId: roomId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i5.ChatRoom>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.ChatRoom>> updateChatRoom({
    required String? roomId,
    String? name,
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChatRoom,
          [],
          {
            #roomId: roomId,
            #name: name,
            #description: description,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i5.ChatRoom>>.value(
            _FakeEither_0<_i6.Failure, _i5.ChatRoom>(
          this,
          Invocation.method(
            #updateChatRoom,
            [],
            {
              #roomId: roomId,
              #name: name,
              #description: description,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i5.ChatRoom>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> deleteChatRoom(
          {required String? roomId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteChatRoom,
          [],
          {#roomId: roomId},
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #deleteChatRoom,
            [],
            {#roomId: roomId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);
}
